### ISSUE TITLE
test environment (very very important)

### ISSUE THREAD

**Issue by avelino** [avelino/cover.run#11]
Host: TravisCI
When receiving a new PR we need to ensure that it does not break the functions that already exist

**Comment by avelino** [comment]
@pascaldekloe @bnkamalesh help this issue?

**Comment by pascaldekloe** [comment]
Do you mean a place to host @avelino?

**Comment by bnkamalesh** [comment]
@avelino could you please elaborate the issue?

Edit: https://github.com/avelino/cover.run/pull/12

**Comment by bnkamalesh** [comment]
https://github.com/avelino/cover.run/pull/12
