### ISSUE TITLE
local static badge

### ISSUE THREAD

**Issue by avelino** [avelino/cover.run#16]
Proxying badges is causing us more trouble than keeping local.

Write script (eg bash) to download all necessary badge 0% to 100% (whit color rules)

Repository url call image on assets URI

**Comment by bnkamalesh** [comment]
https://github.com/avelino/cover.run/pull/15 Solved! And some added bonus too, there are badges showing statuses.

**Comment by avelino** [comment]
Sorry, problem still exists (I did deploy with the latest version)
![screenshot 2018-05-07 08 21 14](https://user-images.githubusercontent.com/31996/39699457-ae460e42-51cf-11e8-8af6-b3cea3e3b2d0.png)

**warning:** In my view we have a lot of complexity in a feature that can be simple with static images

**Comment by bnkamalesh** [comment]
Interesting, is there any CDN or anything else in front of this service? It's a content encoding error. Though it works perfectly fine when running on local.

Edit: SVG handler had a proxy header `w.Header().Set("X-CoverRunProxy", "CoverRunProxy") `. Removed the proxy header, which might fix the issue. Though I don't think it's a complex solution, it's simple text template

**Comment by bnkamalesh** [comment]
It was an HTTP response header problem. Now I've tested on multiple browsers (Edge, Firefox, Google Chrome. The earlier one only worked on Firefox) & it works fine.
