### ISSUE TITLE
badge status: error

### ISSUE THREAD

**Issue by KaiSchwarz-cnic** [avelino/cover.run#19]
https://cover.run/go?repo=github.com%2Fhexonet%2Fgo-sdk&tag=golang-1.10

Maybe you can help me to find out what's going wrong here? Is there something missing that we need in addition? Our sources are in folder "client" and "response" (to represent the package structure) and tests can be found in folder "test".

**Comment by bnkamalesh** [comment]
@papakai cover.run checks for test files in the root of the package only. Since your tests are all inside the `test` directory, cover.run is not able to run tests.

**Comment by KaiSchwarz-cnic** [comment]
@bnkamalesh ty for your response. wouldn't it make sense to also support the test subfolder?
I directly point to [this](https://github.com/golang-standards/project-layout) git project, which points on project standards and having a "test" subfolder is a very common structure. Looking up all `*_test.go` files there (also possible structured in subfolders), would be very great!

**Comment by bitfield** [comment]
Libraries commonly put code (and tests) in a `pkg` folder. How about running `go test ./...`, which will pick up all subfolders?
