### ISSUE TITLE
Queued processing

### ISSUE THREAD

**Issue by avelino** [avelino/cover.run#2]
Today the cover.run `down` when it puts many to rotate, we need a few things rapporteur: 

- queue process (added queue sistema), run 5 jobs concurrent
- frontend used ajax (no html render on Golang)

**Comment by bnkamalesh** [comment]
https://github.com/avelino/cover.run/pull/15 (only queued processing, no Ajax added)

**Comment by avelino** [comment]
fixed on #17 
thanks @bnkamalesh very very good working!
