### ISSUE TITLE
Bug report: label says error for my package

### ISSUE THREAD

**Issue by pjebs** [avelino/cover.run#25]
For my package: https://cover.run/go?tag=golang-1.10&repo=github.com%2Frocketlaunchr%2Fdataframe-go

The label shows it as error but the description provided says no error.

Gocover shows no such error:
https://gocover.io/github.com/rocketlaunchr/dataframe-go

**Comment by avelino** [comment]
Details

ok github.com/rocketlaunchr/dataframe-go 0.008s coverage: 81.8% of statements ? github.com/rocketlaunchr/dataframe-go/imports [no test files]

**Comment by pjebs** [comment]
Yes

**Comment by sgreben** [comment]
For me as well: ![error](https://cover.run/go/github.com/sgreben/piecewiselinear.svg?style=flat&tag=golang-1.10&d=1540129660812)

https://cover.run/go?repo=github.com%2Fsgreben%2Fpiecewiselinear&tag=golang-1.10

> Details
> ok github.com/sgreben/piecewiselinear 0.002s coverage: 94.4% of statements

**Comment by pjebs** [comment]
It was actually working a week ago. Then magically stopped working.

**Comment by wzshiming** [comment]
The same question

**Comment by avelino** [comment]
Hey peoples fixed by @cloudson (very thanks man)

**Comment by sgreben** [comment]
Perfect, thanks @cloudson & @avelino :)
