### ISSUE TITLE
Badge not loading

### ISSUE THREAD

**Issue by bnkamalesh** [avelino/cover.run#4]
Hello @avelino, I've added a badge on my repo, but it stopped showing the badge. The image is not loading properly. ~~I use cover.run badge on other project and they work fine.~~

https://cover.run/go/github.com/bnkamalesh/webgo.svg?tag=golang-1.10 <- badge image url, which works fine when directly opened in browser.

Repository in question: https://github.com/bnkamalesh/webgo

Edit: all my repos stopped showing the badge.
https://github.com/bnkamalesh/benchmark
https://github.com/bnkamalesh/routinepool
https://github.com/bnkamalesh/currency

**Comment by avelino** [comment]
Need to create a cache of the generated images, today we do redirect to `shields.io`

**Comment by bnkamalesh** [comment]
I just checked the size of a badge, it's ~700bytes. That means, with just 256MB of space, we can store 300,000+ badges ( 256 * 1024 * 1024 / 700). In which case, we could just save raw bytes in Redis and serve the file, without redirecting to shields.io. Shields.io responds in 1.5+ seconds (in India at least, and I'm on a 100Mbps connection).

Edit: adding the PR which would cache badges https://github.com/avelino/cover.run/pull/7
